// Spanish translations for Flutter intl localization
// This file should be generated by Flutter's intl tools or edited to match the AppLocalizations interface.

// If you use ARB files, this Dart file is not needed. If you use manual localization, implement only the intl method here.
